apiVersion: v1
kind: Namespace
metadata:
  name: prd-blog
---
apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-frontend
  namespace: prd-blog
#  annotations:
#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dsandrade.info
    secretName: blog-cert
  rules:
  - host: dsandrade.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog-frontend
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog-frontend
  namespace: prd-blog
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http 
  selector:
    app: blog-frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
  namespace: prd-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-frontend
  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      containers:
      - name: blog-frontend
        image: us-central1-docker.pkg.dev/svc-79/images/blog-frontend
        ports:
          - name: http
            containerPort: 80
