
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "us-central1-docker.pkg.dev/svc-79/images/blog-frontend", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "us-central1-docker.pkg.dev/svc-79/images/blog-frontend"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'manifests/blog.yaml'
      - '--namespace'
      - 'prd-blog'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=apps-prd'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'restart'
      - 'deployment/blog-frontend'
      - '--namespace'
      - 'prd-blog'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=apps-prd'

logsBucket: gs://814312266533.cloudbuild-logs.googleusercontent.com