steps:
  - name: 'gcr.io/cloud-builders/npm:12.22.2-buster-slim'
    entrypoint: 'npm'
    args: ["install"]
  - name: 'gcr.io/cloud-builders/npm:12.22.2-buster-slim'
    entrypoint: 'npm'
    args: [ "run", "build" ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "us-central1-docker.pkg.dev/svc-79/images/blog-frontend", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "us-central1-docker.pkg.dev/svc-79/images/blog-frontend"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'restart'
      - 'deployment/blog'
      - '--namespace'
      - 'blog'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=apps-dev'
